### ISSUE TITLE
Flatcar may inadvertently update during image creation

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/image-builder#854]
In https://github.com/kubernetes-sigs/image-builder/pull/701/commits/c73b6e7a28b93dd03a747a8454600838e656ff5c we've disabled Flatcar updates. However, this change leaves a time gap which still allows Flatcar to download updates and reboot **during image creation**, resulting in either a broken build or an image with an unexpected version.

Following is a high-level description of the Flatcar image build process for ISO-based Packer builds (e.g. QEMU, OVA):

1. We boot Flatcar from an official ISO or base image (e.g. AMI) of a specific Flatcar release.
2. We execute `flatcar-install` while passing an Ignition file and reboot.
3. Flatcar boots from disk.
4. Ansible is executed.
5. An image is created from the provisioned machine and the machine is terminated.

Currently, **Flatcar may inadvertently update between stage 3 and 5** (inclusive). In order to prevent this, we need to disable updates in the Ignition config we pass to `flatcar-install` at **stage 2**.

>NOTE: I've confirmed this bug exists for OVA builds, however it could apply also for AWS and Azure builds: Although these builds aren't based on booting from ISO, there is still a phase where the temporary VM is running while Ansible is executing. We should double-check updates are disabled during that phase, too.

## TODO

- [ ] Ensure updates are disabled throughout the entire build process as well as the final image for all supported providers.
  - [ ] AMI - handled by #1150
  - [ ] Azure (SIG + VHD) - handled by #1150
  - [x] OVA - handled by #895
  - [x] QEMU - handled by #895
  - [x] Raw - handled by #895

/kind bug
/assign

**Comment by johananl** [comment]
Fixed in https://github.com/flatcar-linux/flatcar-packer-qemu/pull/5. Once merged, we need to update the following:

https://github.com/kubernetes-sigs/image-builder/blob/2e85b15e9e75f5a194eb0c4c3f21c47918281a41/images/capi/packer/qemu/qemu-flatcar.json#L3

https://github.com/kubernetes-sigs/image-builder/blob/2e85b15e9e75f5a194eb0c4c3f21c47918281a41/images/capi/packer/raw/raw-flatcar.json#L3

**Comment by johananl** [comment]
Following https://github.com/kubernetes-sigs/image-builder/pull/873#discussion_r866007976, looks like the solution to this issue depends on https://github.com/kubernetes-sigs/image-builder/issues/890.

/hold

**Comment by johananl** [comment]
Fix in https://github.com/kubernetes-sigs/image-builder/pull/1150.
